<a href="https://colab.research.google.com/github/Andresflorezdev/DAT-05_ANALISIS_y_Visualizacion_de_Datos-Esumer-Medellin/blob/main/Taller_Pandas_y_SQL_Ecommerce_ESUMER.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Taller guiado — Pandas aplicado e introducción a SQL
### Caso e-commerce: de la pregunta a la consulta

**Curso:** Analítica y Visualización de Datos para la Toma de Decisiones  
**Sesión:** Clases 4 y 5 integradas  
**Ruta principal:** aproximadamente 55 minutos  
**Extensión SQL:** aproximadamente 20 minutos

## Objetivo

Al terminar podrás:

- importar un archivo CSV;
- reconocer la estructura y los tipos de un DataFrame;
- seleccionar columnas;
- realizar cálculos y crear variables;
- filtrar registros con una o varias condiciones;
- obtener conteos y resúmenes por categoría;
- ordenar resultados;
- ejecutar consultas SQL sencillas sobre los mismos datos.

## Cómo utilizar este notebook

1. Ejecuta las celdas en orden con `Shift + Enter`.
2. Lee la explicación antes del código.
3. Modifica solamente las celdas que indican **COMPLETA AQUÍ**.
4. Compara la salida con el resultado esperado.
5. Escribe una interpretación cuando aparezca la señal 🧠.

### Señales

- 📚 **Recordemos:** concepto necesario.
- 💡 **Ejemplo:** código resuelto.
- ✏️ **Completa aquí:** trabajo del estudiante.
- 👀 **Resultado esperado:** verificación.
- 🧠 **Interpreta:** conecta el resultado con el caso.
- ⚠️ **Error frecuente:** dificultad habitual.
- ⭐ **Extensión:** contenido opcional o introductorio.

# 1. El caso

Una tienda virtual quiere comprender el comportamiento de sus pedidos entre julio y septiembre de 2026.

El archivo `ventas_ecommerce.csv` contiene:

- 96 pedidos;
- 30 clientes;
- 12 columnas originales;
- información sobre ciudad, canal, categoría, cantidades, precios, descuentos, estado y satisfacción.

Algunas preguntas del negocio son:

1. ¿Qué categorías concentran más pedidos?
2. ¿Cuál es el valor total de las ventas?
3. ¿Qué pedidos superan los $300.000?
4. ¿Qué ciudad registra mayor valor neto?
5. ¿Cuáles son los cinco pedidos de mayor valor?

# 2. Preparar el entorno

📚 `pandas` es la librería que utilizaremos para trabajar con datos tabulares.

In [ ]:
import pandas as pd

## Cargar el archivo en Google Colab

1. Abre el panel **Archivos** de la barra izquierda.
2. Selecciona **Subir**.
3. Carga `ventas_ecommerce.csv`.
4. Ejecuta la siguiente celda.

⚠️ Si aparece `FileNotFoundError`, revisa que el archivo esté cargado y que el nombre coincida exactamente.

In [ ]:
nombre_archivo = "ventas_ecommerce.csv"

df = pd.read_csv(nombre_archivo)
df.head()

,pedido_id,cliente_id,fecha_pedido,ciudad,canal_adquisicion,tipo_cliente,categoria_producto,cantidad,precio_unitario,descuento_pct,estado_pedido,satisfaccion
0,PED0001,CLI001,2026-07-21,Medellín,Redes sociales,Recurrente,Libros,3,95000,0,Entregado,3.0
1,PED0002,CLI002,2026-07-07,Medellín,Email,Recurrente,Hogar,1,210000,5,Cancelado,NaN
2,PED0003,CLI003,2026-09-03,Medellín,Redes sociales,Recurrente,Belleza,3,110000,0,Entregado,3.0
3,PED0004,CLI004,2026-08-13,Medellín,Google,Recurrente,Tecnología,3,180000,0,Entregado,5.0
4,PED0005,CLI005,2026-07-19,Itagüí,Redes sociales,Recurrente,Hogar,1,135000,0,Entregado,4.0

👀 **Resultado esperado:** una tabla con las primeras cinco filas y 12 columnas.

📚 En la instrucción anterior:

- `pd` es el alias de Pandas;
- `read_csv()` lee el archivo;
- `df` almacena el DataFrame resultante.

# 3. Inspeccionar antes de calcular

## 3.1 Tamaño de la tabla

In [ ]:
df.shape

(96, 12)

👀 **Resultado esperado:** `(96, 12)`

- `96` corresponde a las filas.
- `12` corresponde a las columnas.

✏️ **Completa aquí:** guarda por separado la cantidad de filas y columnas.

In [ ]:
# COMPLETA AQUÍ
cantidad_filas = df.shape[0]
cantidad_columnas = df.shape[1]

cantidad_filas, cantidad_columnas

(96, 12)

👀 **Resultado esperado:** `(96, 12)`

## 3.2 Nombres de las columnas

In [ ]:
df.columns.tolist()

['pedido_id',
 'cliente_id',
 'fecha_pedido',
 'ciudad',
 'canal_adquisicion',
 'tipo_cliente',
 'categoria_producto',
 'cantidad',
 'precio_unitario',
 'descuento_pct',
 'estado_pedido',
 'satisfaccion']

🧠 Identifica cuáles columnas parecen:

- identificadores;
- categorías;
- medidas numéricas;
- fechas.

## 3.3 Tipos de datos

In [ ]:
df.dtypes

pedido_id                     object
cliente_id                    object
fecha_pedido          datetime64[ns]
ciudad                        object
canal_adquisicion             object
tipo_cliente                  object
categoria_producto            object
cantidad                       int64
precio_unitario                int64
descuento_pct                  int64
estado_pedido                 object
satisfaccion                 float64
dtype: object

📚 Algunos tipos que observarás:

- `object`: generalmente texto;
- `int64`: números enteros;
- `float64`: números decimales.

La fecha fue leída inicialmente como texto. La convertiremos.

In [ ]:
df["fecha_pedido"] = pd.to_datetime(df["fecha_pedido"])

df["fecha_pedido"].dtype

dtype('<M8[ns]')

👀 **Resultado esperado:** un tipo relacionado con `datetime64`.

## 3.4 Resumen técnico

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   pedido_id           96 non-null     object
 1   cliente_id          96 non-null     object
 2   fecha_pedido        96 non-null     datetime64[ns]
 3   ciudad              96 non-null     object
 4   canal_adquisicion   96 non-null     object
 5   tipo_cliente        96 non-null     object
 6   categoria_producto  96 non-null     object
 7   cantidad            96 non-null     int64
 8   precio_unitario     96 non-null     int64
 9   descuento_pct       96 non-null     int64
 10  estado_pedido       96 non-null     object
 11  satisfaccion        80 non-null     float64
dtypes: datetime64[ns](1), float64(1), int64(3), object(7)
memory usage: 9.1+ KB

🧠 Observa que `satisfaccion` tiene menos valores disponibles porque los pedidos no entregados todavía no tienen calificación.

# 4. Seleccionar columnas

## 4.1 Una columna produce una Serie

In [ ]:
df["ciudad"].head()

0    Medellín
1    Medellín
2    Medellín
3    Medellín
4      Itagüí
Name: ciudad, dtype: object

## 4.2 Una lista de columnas produce otro DataFrame

In [ ]:
columnas_interes = [
    "pedido_id",
    "ciudad",
    "categoria_producto",
    "cantidad",
    "precio_unitario"
]

df[columnas_interes].head()

  pedido_id    ciudad categoria_producto  cantidad  precio_unitario
0   PED0001  Medellín             Libros         3            95000
1   PED0002  Medellín              Hogar         1           210000
2   PED0003  Medellín            Belleza         3           110000
3   PED0004  Medellín         Tecnología         3           180000
4   PED0005    Itagüí              Hogar         1           135000

✏️ **Completa aquí:** selecciona `pedido_id`, `estado_pedido` y `satisfaccion`.

In [ ]:
# COMPLETA AQUÍ
columnas_estado = ["pedido_id", "estado_pedido", "satisfaccion"]

df[columnas_estado].head()

  pedido_id estado_pedido  satisfaccion
0   PED0001     Entregado           3.0
1   PED0002     Cancelado           NaN
2   PED0003     Entregado           3.0
3   PED0004     Entregado           5.0
4   PED0005     Entregado           4.0

👀 **Resultado esperado:** una tabla de cinco filas y tres columnas.

# 5. Operaciones básicas

## 5.1 Sumar cantidades

In [ ]:
total_unidades = df["cantidad"].sum()
total_unidades

np.int64(240)

👀 **Resultado esperado:** `240`

## 5.2 Precio promedio

In [ ]:
precio_promedio = df["precio_unitario"].mean()
round(precio_promedio, 2)

np.float64(155760.42)

👀 **Resultado esperado:** aproximadamente `155760.42`

✏️ **Completa aquí:** calcula la satisfacción promedio. Pandas ignorará automáticamente los valores faltantes.

In [ ]:
# COMPLETA AQUÍ
satisfaccion_promedio = df["satisfaccion"].mean()
round(satisfaccion_promedio, 2)

np.float64(4.14)

👀 **Resultado esperado:** aproximadamente `4.14`

🧠 Este promedio corresponde únicamente a los pedidos que tienen calificación.

# 6. Crear nuevas variables

## 6.1 Valor bruto

El valor bruto de un pedido se calcula multiplicando cantidad por precio unitario.

In [ ]:
df["valor_bruto"] = df["cantidad"] * df["precio_unitario"]

df[["cantidad", "precio_unitario", "valor_bruto"]].head()

   cantidad  precio_unitario  valor_bruto
0         3            95000       285000
1         1           210000       210000
2         3           110000       330000
3         3           180000       540000
4         1           135000       135000

## 6.2 Valor del descuento

El porcentaje debe convertirse a una proporción dividiéndolo por 100.

In [ ]:
df["valor_descuento"] = (
    df["valor_bruto"] * df["descuento_pct"] / 100
)

df[["valor_bruto", "descuento_pct", "valor_descuento"]].head()

   valor_bruto  descuento_pct  valor_descuento
0       285000              0              0.0
1       210000              5          10500.0
2       330000              0              0.0
3       540000              0              0.0
4       135000              0              0.0

✏️ **Completa aquí:** crea `valor_neto` restando el descuento al valor bruto.

In [ ]:
# COMPLETA AQUÍ
df["valor_neto"] = df["valor_bruto"] - df["valor_descuento"]

df[["valor_bruto", "valor_descuento", "valor_neto"]].head()

   valor_bruto  valor_descuento  valor_neto
0       285000              0.0    285000.0
1       210000          10500.0    199500.0
2       330000              0.0    330000.0
3       540000              0.0    540000.0
4       135000              0.0    135000.0

👀 **Resultado esperado para el primer pedido:** valor bruto y valor neto de `$285.000`, porque no tiene descuento.

Para continuar, la siguiente celda crea la variable completa por si todavía no terminaste el ejercicio.

In [ ]:
# Celda de continuidad
df["valor_neto"] = df["valor_bruto"] - df["valor_descuento"]

round(df["valor_neto"].sum(), 0)

np.float64(33505500.0)

👀 **Resultado esperado:** `33505500`

🧠 El valor neto total de los 96 pedidos es $33.505.500.

# 7. Construir condiciones y filtros

## 7.1 Una condición produce valores booleanos

In [ ]:
condicion_valor_alto = df["valor_neto"] >= 300000

condicion_valor_alto.head()

0    False
1    False
2     True
3     True
4    False
Name: valor_neto, dtype: bool

👀 **Resultado esperado:** una Serie con valores `True` y `False`.

## 7.2 Utilizar la condición para filtrar

In [ ]:
pedidos_valor_alto = df[condicion_valor_alto]

len(pedidos_valor_alto)

39

👀 **Resultado esperado:** `39`

✏️ **Completa aquí:** filtra únicamente los pedidos entregados.

In [ ]:
# COMPLETA AQUÍ
pedidos_entregados = df[df["estado_pedido"] == "Entregado"]

len(pedidos_entregados)

80

👀 **Resultado esperado:** `80`

## 7.3 Combinar condiciones

En Pandas:

- `&` significa **y**;
- `|` significa **o**;
- cada condición debe ir entre paréntesis.

In [ ]:
filtro_medellin_alto = (
    (df["ciudad"] == "Medellín") &
    (df["valor_neto"] >= 300000)
)

pedidos_medellin_altos = df[filtro_medellin_alto]
len(pedidos_medellin_altos)

23

👀 **Resultado esperado:** `23`

✏️ **Completa aquí:** cuenta los pedidos que tienen descuento y un valor neto igual o superior a $300.000.

In [ ]:
# COMPLETA AQUÍ
filtro_descuento_alto = (
    (df["descuento_pct"] > 0) & \
    (df["valor_neto"] >= 300000)
)

len(df[filtro_descuento_alto])

23

👀 **Resultado esperado:** `23`

# 8. Conteos y resúmenes

## 8.1 Frecuencias por categoría

In [ ]:
pedidos_por_categoria = df["categoria_producto"].value_counts()
pedidos_por_categoria

categoria_producto
Hogar         27
Tecnología    23
Libros        19
Deporte       14
Belleza       13
Name: count, dtype: int64

👀 **Resultado esperado:**

| Categoría | Pedidos |
|---|---:|
| Hogar | 27 |
| Tecnología | 23 |
| Libros | 19 |
| Deporte | 14 |
| Belleza | 13 |

🧠 Hogar es la categoría más frecuente. Esto todavía no demuestra que sea la categoría con mayor valor vendido.

✏️ **Completa aquí:** cuenta los pedidos por estado.

In [ ]:
# COMPLETA AQUÍ
df["estado_pedido"].value_counts()

estado_pedido
Entregado      80
En tránsito     9
Cancelado       7
Name: count, dtype: int64

👀 **Resultado esperado:** 80 entregados, 9 en tránsito y 7 cancelados.

## 8.2 Resumir por grupo

`groupby()` divide la tabla por categorías y aplica una operación a cada grupo.

In [ ]:
ventas_por_ciudad = (
    df.groupby("ciudad")["valor_neto"]
      .sum()
      .sort_values(ascending=False)
)

ventas_por_ciudad

ciudad
Medellín    21298100.0
Envigado     5569200.0
Itagüí       5416200.0
Bello        1222000.0
Name: valor_neto, dtype: float64

👀 **Resultado esperado:** Medellín aparece primero con `$21.298.100`.

✏️ **Completa aquí:** calcula el valor neto total por categoría de producto y ordénalo de mayor a menor.

In [ ]:
# COMPLETA AQUÍ
ventas_por_categoria = (
    df.groupby("categoria_producto")["valor_neto"]
      .sum()
      .sort_values(ascending=False)
)

ventas_por_categoria

categoria_producto
Tecnología    12325000.0
Hogar         12110250.0
Deporte        3627500.0
Belleza        2911500.0
Libros         2531250.0
Name: valor_neto, dtype: float64

👀 **Resultado esperado:** Tecnología aparece primero con `$12.325.000`, seguida de Hogar con `$12.110.250`.

# 9. Ordenar y seleccionar los primeros registros

Queremos identificar los cinco pedidos con mayor valor neto.

In [ ]:
top_5_pedidos = (
    df.sort_values("valor_neto", ascending=False)
      .head(5)
)

top_5_pedidos[
    ["pedido_id", "ciudad", "categoria_producto", "valor_neto"]
]

   pedido_id    ciudad categoria_producto  valor_neto
31   PED0032  Medellín         Tecnología   1428000.0
63   PED0064  Medellín              Hogar   1280000.0
56   PED0057    Itagüí         Tecnología   1170000.0
85   PED0086  Medellín         Tecnología   1134000.0
83   PED0084    Itagüí              Hogar   1024000.0

👀 **Resultado esperado:** `PED0032` ocupa el primer lugar con `$1.428.000`.

🧠 Un ranking combina ordenamiento y selección. `head(5)` conserva los cinco primeros registros después de ordenar.

# 10. Reto integrador de Pandas

Elige una pregunta:

### Opción A
¿Qué ciudad registra el mayor valor neto de ventas?

### Opción B
¿Qué categoría tiene el mayor número de pedidos?

### Opción C
¿Cuántos pedidos con descuento superan o igualan los $300.000?

## Entregable

1. Escribe la pregunta elegida.
2. Selecciona las columnas necesarias.
3. Construye el código.
4. Muestra el resultado.
5. Escribe una interpretación.
6. Formula una nueva pregunta.

In [ ]:
# COMPLETA AQUÍ
# Escribe el código necesario para responder la pregunta elegida.
# ¿Qué ciudad registra el mayor valor neto de ventas?

ciudad_con_mayor_valor_neto = (
    df.groupby("ciudad")["valor_neto"]
    .sum()
    .sort_values(ascending=False)
)
ciudad_con_mayor_valor_neto

ciudad
Medellín    21298100.0
Envigado     5569200.0
Itagüí       5416200.0
Bello        1222000.0
Name: valor_neto, dtype: float64

In [ ]:
# COMPLETA AQUÍ
# Escribe el código necesario para responder la pregunta elegida.
# ¿Qué categoría tiene el mayor número de pedidos?

df["categoria_producto"].value_counts()

categoria_producto
Hogar         27
Tecnología    23
Libros        19
Deporte       14
Belleza       13
Name: count, dtype: int64

In [ ]:
# COMPLETA AQUÍ
# Escribe el código necesario para responder la pregunta elegida.
# ¿Cuántos pedidos con descuento superan o igualan los $300.000?

pedidos_filtrados = df[
    (df["descuento_pct"] > 0) &
    (df["valor_neto"] >= 300000)
]
numero_de_pedidos = len(pedidos_filtrados)
numero_de_pedidos

23

# ⭐ 11. Introducción a datos relacionales

Hasta ahora trabajamos con una tabla plana que contiene información del cliente y del pedido en cada fila.

Una base relacional puede separar esta información:

## Tabla `clientes`

- `cliente_id`: clave primaria.
- `ciudad`.
- `canal_adquisicion`.
- `tipo_cliente`.

## Tabla `pedidos`

- `pedido_id`: clave primaria.
- `cliente_id`: clave foránea.
- datos del pedido.

La relación es:

> Un cliente puede realizar varios pedidos.

In [ ]:
clientes = (
    df[[
        "cliente_id",
        "ciudad",
        "canal_adquisicion",
        "tipo_cliente"
    ]]
    .drop_duplicates()
    .reset_index(drop=True)
)

pedidos = df[[
    "pedido_id",
    "cliente_id",
    "fecha_pedido",
    "categoria_producto",
    "cantidad",
    "precio_unitario",
    "descuento_pct",
    "estado_pedido",
    "satisfaccion",
    "valor_neto"
]].copy()

len(clientes), len(pedidos)

👀 **Resultado esperado:** `(30, 96)`

La primera tabla tiene un registro por cliente. La segunda tiene un registro por pedido.

# 12. Ejecutar SQL en Google Colab

Utilizaremos SQLite, una base de datos ligera incluida en Python.

In [ ]:
import sqlite3

conexion = sqlite3.connect(":memory:")

clientes.to_sql("clientes", conexion, index=False, if_exists="replace")
pedidos.to_sql("pedidos", conexion, index=False, if_exists="replace")

📚 Acabamos de crear dos tablas dentro de una base SQLite temporal.

## Anatomía de una consulta

```sql
SELECT columnas
FROM tabla
WHERE condición
ORDER BY columna
LIMIT cantidad;
```

- `SELECT`: columnas que queremos.
- `FROM`: tabla que consultaremos.
- `WHERE`: registros que cumplen la condición.
- `ORDER BY`: orden del resultado.
- `LIMIT`: cantidad máxima de filas.

## 12.1 Primer ejemplo: pedidos de valor alto

In [ ]:
consulta_1 = """
SELECT pedido_id, categoria_producto, valor_neto
FROM pedidos
WHERE valor_neto >= 300000
ORDER BY valor_neto DESC
LIMIT 5;
"""

pd.read_sql_query(consulta_1, conexion)

👀 **Resultado esperado:** una tabla con cinco pedidos. `PED0032` aparece primero.

## 12.2 Segundo ejemplo: dos condiciones

In [ ]:
consulta_2 = """
SELECT pedido_id, categoria_producto, estado_pedido, valor_neto
FROM pedidos
WHERE estado_pedido = 'Entregado'
  AND valor_neto >= 300000
ORDER BY valor_neto DESC
LIMIT 5;
"""

pd.read_sql_query(consulta_2, conexion)

📚 En SQL utilizamos `AND` donde Pandas utiliza `&`.

## 12.3 Comparar SQL y Pandas

La consulta equivalente en Pandas sería:

In [ ]:
resultado_pandas = (
    pedidos[
        (pedidos["estado_pedido"] == "Entregado") &
        (pedidos["valor_neto"] >= 300000)
    ]
    .sort_values("valor_neto", ascending=False)
    .head(5)
)

resultado_pandas[
    ["pedido_id", "categoria_producto", "estado_pedido", "valor_neto"]
]

🧠 Ambos lenguajes devuelven el mismo resultado. Cambia la forma de expresar la consulta.

## 12.4 Mini ejercicio SQL

Completa la consulta para obtener los tres pedidos cancelados de mayor valor.

In [ ]:
# COMPLETA AQUÍ
consulta_3 = """
SELECT pedido_id, estado_pedido, valor_neto
FROM pedidos
WHERE estado_pedido = '____________'
ORDER BY valor_neto ____
LIMIT ____;
"""

pd.read_sql_query(consulta_3, conexion)

👀 **Resultado esperado:** tres filas, ordenadas desde el pedido cancelado de mayor valor.

# 13. Cierre

Hoy trabajaste la misma lógica mediante dos lenguajes:

## Pandas

- selecciona y transforma DataFrames;
- facilita la exploración y el análisis en Python.

## SQL

- consulta tablas almacenadas en una base de datos;
- utiliza cláusulas para definir qué resultado necesita.

La secuencia común es:

**pregunta → tabla → operación o consulta → resultado → interpretación**

Antes de terminar, escribe en una celda Markdown:

1. Una operación de Pandas que puedas explicar.
2. Una cláusula SQL que reconozcas.
3. Una diferencia entre DataFrame y tabla de base de datos.
4. Una duda para la siguiente clase.